const Router = require("express").Router()
const UserRouter = require("./UserRouter")
const ProfileRouter = require("./ProfileRouter")
const SkillRouter = require("./SkillRouter")
const CatsRouter = require("./CategoryRouter")
Router.use("/users", UserRouter)
Router.use("/profiles", ProfileRouter)
Router.use("/skills", SkillRouter)
Router.use("/cats", CatsRouter)
module.exports = Router
